server:
 port: 8080

app: 
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 1800000

spring:
 datasource:
  username: root
  url: jdbc:mysql://localhost:3306/kanpm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  driver-class-name: com.mysql.cj.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  

mybatis:
 mapper-locations:
  - classpath:mapping/*Mapper.xml
 type-aliases-package: com.locotor.kanpm.entities
 configuration:
    use-generated-keys: true